name: Data Schema Code Convention

on:
  push:
    branches: [ LW4 ]

jobs:
  sql_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run SQLFluff Linter
        run: |
          pip install sqlfluff
          echo "=== SQL Linter Results ==="
          sqlfluff lint $GITHUB_WORKSPACE/2-SoftwareDesign/2.4-DetailedDataSchema/RelationDB_DetailedDataSchema.sql --dialect oracle