name: Data Schema Code Convention

on:
  push:
    branches: [ laboratory-work-4 ]
  pull_request:
    branches: [ laboratory-work-4 ]
  workflow_dispatch:

jobs:
  SQLLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install SQLFluff
        run: python -m pip install sqlfluff

      - name: Lint SQL schema
        run: python -m sqlfluff lint "$GITHUB_WORKSPACE/2-SoftwareDesign/2.4-DetailedDataSchema/RelationDB_DetailedDataSchema.sql" --dialect oracle --exclude-rules L039,L052