name: Print Software Versions

on:
  push:
    branches: [ laboratory-work-4 ]
  pull_request:
    branches: [ laboratory-work-4 ]
  workflow_dispatch:

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java -version

      - name: Print Node.js Version
        run: node --version

      - name: Print Python Version
        run: python3 --version

  PrintDBMSVersions:
    needs: PrintLanguageVersions
    runs-on: ubuntu-latest
    steps:
      - name: Print PostgreSQL Version
        run: psql --version

      - name: Print MySQL Version
        run: mysql --version

      - name: Print MongoDB Version
        run: mongod --version